#!/usr/bin/env sh

mkdir -p ~/.claude
mkdir -p ~/.gsd

cp -Rf ~/.dotfiles-origin/claude/* ~/.claude/
cp -Rf ~/.dotfiles-origin/gsd/* ~/.gsd/

if [ ! -d ~/installation ]; then
  echo "Installing thamw/get-stuff-done main"
  git clone https://git.tham.one/thamw/get-stuff-done.git ~/installation
else
  echo "thamw/get-stuff-done already present, pulling latest"
fi
cd ~/installation
git checkout main
git pull
npm install
npm run build
node bin/install.js --global --claude
echo "Installation thamw/gsd-core main DONE!"
cd

echo "~/personalize done!"
